# Generated by Django 5.0.2 on 2024-04-26 18:40

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('weight', models.IntegerField(default=0)),
                ('hitpoints', models.IntegerField(default=100)),
                ('is_default', models.BooleanField(default=False)),
                ('effects', models.JSONField(default=inventory.models.default_effects_for_item)),
            ],
        ),
    ]
