# Generated by Django 5.0.2 on 2024-04-26 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('oblivionalchemy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryinstance',
            name='character_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='oblivionalchemy.character'),
        ),
    ]
