# Generated by Django 5.0.2 on 2024-04-26 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0001_initial'),
        ('oblivionalchemy', '0002_alter_character_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='character',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='discord_user', to='oblivionalchemy.character'),
        ),
    ]
