# Generated by Django 5.0.2 on 2024-04-26 21:15

import django.db.models.deletion
import oblivionalchemy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('strength', models.IntegerField(default=10)),
                ('endurance', models.IntegerField(default=10)),
                ('agility', models.IntegerField(default=10)),
                ('speed', models.IntegerField(default=10)),
                ('willpower', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('personality', models.IntegerField(default=10)),
                ('luck', models.IntegerField(default=10)),
                ('alchemy', models.IntegerField(default=10)),
                ('survival', models.IntegerField(default=10)),
                ('blade', models.IntegerField(default=10)),
                ('marksman', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('weight', models.IntegerField(default=0)),
                ('hitpoints', models.IntegerField(default=100)),
                ('is_default', models.BooleanField(default=False)),
                ('effects', models.JSONField(default=oblivionalchemy.models.default_effects_for_item)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=100, unique=True)),
                ('character', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='discord_user', to='oblivionalchemy.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='oblivionalchemy.discorduser'),
        ),
        migrations.CreateModel(
            name='InventoryInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=dict)),
                ('character_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='oblivionalchemy.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='inventory_instance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='oblivionalchemy.inventoryinstance'),
        ),
    ]
