# Generated by Django 5.0.2 on 2024-02-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('strength', models.IntegerField(default=10)),
                ('endurance', models.IntegerField(default=10)),
                ('agility', models.IntegerField(default=10)),
                ('speed', models.IntegerField(default=10)),
                ('willpower', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('personality', models.IntegerField(default=10)),
                ('luck', models.IntegerField(default=10)),
            ],
        ),
    ]
