# Generated by Django 5.0.2 on 2024-02-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oblivionalchemy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='alchemy',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='blade',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='marksman',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='survival',
            field=models.IntegerField(default=10),
        ),
    ]
