# Generated by Django 5.0.2 on 2024-04-19 07:25

import django.db.models.deletion
import oblivionalchemy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '__first__'),
        ('oblivionalchemy', '0002_character_alchemy_character_blade_character_marksman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='inventory_instance',
            field=models.JSONField(default=oblivionalchemy.models.default_inventory),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='discordbot.user'),
        ),
    ]
