# Generated by Django 5.0.2 on 2024-04-13 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '__first__'),
        ('inventory', '__first__'),
        ('oblivionalchemy', '0002_character_alchemy_character_blade_character_marksman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='inventory_instance',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.inventoryinstance'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='discordbot.user'),
        ),
    ]
