# Generated by Django 5.0.2 on 2024-04-13 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '__first__'),
        ('oblivionalchemy', '0003_character_inventory_instance_character_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='inventory_instance',
            field=models.OneToOneField(default={}, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.inventoryinstance'),
        ),
    ]
