# Generated by Django 5.0.2 on 2024-04-13 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '__first__'),
        ('oblivionalchemy', '0005_alter_character_inventory_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='inventory_instance',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='inventory.inventoryinstance'),
        ),
    ]
