from colorama import Fore, Style

def color_text(text, color):
    color_map = {
        'RED': Fore.RED,
        'CYAN': Fore.CYAN,
        'GREEN': Fore.GREEN,
        'YELLOW': Fore.YELLOW,
    }
    
    color = color_map.get(color.upper(), Fore.RESET)
    return f'{color}{text}{Style.RESET_ALL}'


emojimap = {
'cure_poison':'cure',
'cure_disease':'cure',
'cure_paralysis':'cure',
'fortify_magicka':'fortify_magicka',
'fortify_intelligence':'fortify',
'fortify_willpower':'fortify',
'fortify_strength':'fortify',
'fortify_speed':'fortify',
'fortify_agility':'fortify',
'fortify_health':'fortify',
'fortify_speed':'fortify',
'fortify_luck':'fortify',
'fortify_personality':'fortify',
'fortify_fatigue':'fortify',
'fortify_endurance':'fortify',
'burden':'burden',
'frost_damage':'frost',
'shock_damage':'shock',
'feather':'feather',
'fire_damage':'fire',
'dispel':'dispel',
'shield':'shield',
'resist_paralysis':'resist_element',
'resist_poison':'resist_element',
'resist_disease':'resist_element',
'resist_frost':'resist_element',
'resist_fire':'resist_element',
'resist_shock':'resist_element',
'frost_shield':'frost_shield',
'shock_shield':'shock_shield',
'fire_shield':'fire_shield',
'silence':'silence',
'reflect_damage':'reflect_damage',
'reflect_spell':'reflect_spell',
'invisibility':'invisibility',
'restore_fatigue':'restore',
'restore_magicka':'restore',
'restore_health':'restore',
'restore_strength':'restore',
'restore_willpower':'restore',
'restore_speed':'restore',
'restore_personality':'restore',
'restore_intelligence':'restore',
'restore_agility':'restore',
'restore_endurance':'restore',
'restore_luck':'restore',
'burden':'burden',
'water_breathing':'water_breathing',
'water_walking':'water_walking',
'silence':'silence',
'night-eye':'night_eye',
'damage_agility':'damage_attribute',
'damage_endurance':'damage_attribute',
'damage_fatigue':'damage_attribute',
'damage_strength':'damage_attribute',
'damage_magicka':'damage_attribute',
'damage_willpower':'damage_attribute',
'damage_health':'damage_attribute',
'damage_luck':'damage_attribute',
'damage_intelligence':'damage_attribute',
'damage_personality':'damage_attribute',
'damage_speed':'damage_attribute',
'detect_life':'detect_life',
'chameleon':'chameleon',
'paralyze':'paralyze',
'light':'light',
}

effects_dataframe_data = [
    {"effect": "burden", "base_cost": 0.21, "polarity": "negative", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Alteration"},
    {"effect": "chameleon", "base_cost": 0.63, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Illusion"},
    {"effect": "cure_disease", "base_cost": 1400, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": False, "school": "Restoration"},
    {"effect": "cure_paralysis", "base_cost": 500, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": False, "school": "Restoration"},
    {"effect": "cure_poison", "base_cost": 600, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": False, "school": "Restoration"},
    {"effect": "damage_agility", "base_cost": 100, "polarity": "negative", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Destruction"},
    {"effect": "damage_endurance", "base_cost": 100, "polarity": "negative", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Destruction"},
    {"effect": "damage_fatigue", "base_cost": 4.4, "polarity": "negative", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Destruction"},
    {"effect": "damage_health", "base_cost": 12, "polarity": "negative", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Destruction"},
    {"effect": "damage_intelligence", "base_cost": 100, "polarity": "negative", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Destruction"},
    {"effect": "damage_luck", "base_cost": 100, "polarity": "negative", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Destruction"},
    {"effect": "damage_magicka", "base_cost": 2.45, "polarity": "negative", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Destruction"},
    {"effect": "damage_personality", "base_cost": 100, "polarity": "negative", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Destruction"},
    {"effect": "damage_speed", "base_cost": 100, "polarity": "negative", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Destruction"},
    {"effect": "damage_strength", "base_cost": 100, "polarity": "negative", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Destruction"},
    {"effect": "damage_willpower", "base_cost": 100, "polarity": "negative", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Destruction"},
    {"effect": "detect_life", "base_cost": 0.08, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Mysticism"},
    {"effect": "dispel", "base_cost": 3.6, "polarity": "positive", "duration_only": False, "magnitude_only": True, "normal": False, "school": "Mysticism"},
    {"effect": "feather", "base_cost": 0.01, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Alteration"},
    {"effect": "fire_damage", "base_cost": 7.5, "polarity": "negative", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Destruction"},
    {"effect": "fire_shield", "base_cost": 0.95, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Destruction"},
    {"effect": "fortify_agility", "base_cost": 0.6, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "fortify_endurance", "base_cost": 0.6, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "fortify_fatigue", "base_cost": 0.04, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "fortify_health", "base_cost": 0.14, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "fortify_intelligence", "base_cost": 0.6, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "fortify_luck", "base_cost": 0.6, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "fortify_magicka", "base_cost": 0.15, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "fortify_personality", "base_cost": 0.6, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "fortify_speed", "base_cost": 0.6, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "fortify_strength", "base_cost": 0.6, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "fortify_willpower", "base_cost": 0.6, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "frost_damage", "base_cost": 7.4, "polarity": "negative", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Destruction"},
    {"effect": "frost_shield", "base_cost": 0.95, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Destruction"},
    {"effect": "invisibility", "base_cost": 40, "polarity": "positive", "duration_only": True, "magnitude_only": False, "normal": False, "school": "Illusion"},
    {"effect": "light", "base_cost": 0.051, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Illusion"},
    {"effect": "night-eye", "base_cost": 22, "polarity": "positive", "duration_only": True, "magnitude_only": False, "normal": False, "school": "Mysticism"},
    {"effect": "paralyze", "base_cost": 475, "polarity": "negative", "duration_only": True, "magnitude_only": False, "normal": False, "school": "Illusion"},
    {"effect": "reflect_damage", "base_cost": 2.5, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Mysticism"},
    {"effect": "reflect_spell", "base_cost": 3.5, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Mysticism"},
    {"effect": "resist_disease", "base_cost": 0.5, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "resist_fire", "base_cost": 0.5, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "resist_frost", "base_cost": 0.5, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "resist_paralysis", "base_cost": 0.75, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "resist_poison", "base_cost": 0.5, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "resist_shock", "base_cost": 0.5, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "restore_agility", "base_cost": 38, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "restore_endurance", "base_cost": 38, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "restore_fatigue", "base_cost": 2, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "restore_health", "base_cost": 10, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "restore_intelligence", "base_cost": 38, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "restore_luck", "base_cost": 38, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "restore_magicka", "base_cost": 2.5, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "restore_personality", "base_cost": 38, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "restore_speed", "base_cost": 38, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "restore_strength", "base_cost": 38, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "restore_willpower", "base_cost": 38, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Restoration"},
    {"effect": "shield", "base_cost": 0.45, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Alteration"},
    {"effect": "shock_damage", "base_cost": 7.8, "polarity": "negative", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Destruction"},
    {"effect": "shock_shield", "base_cost": 0.95, "polarity": "positive", "duration_only": False, "magnitude_only": False, "normal": True, "school": "Destruction"},
    {"effect": "silence", "base_cost": 60, "polarity": "negative", "duration_only": True, "magnitude_only": False, "normal": False, "school": "Illusion"},
    {"effect": "water_breathing", "base_cost": 14.5, "polarity": "positive", "duration_only": True, "magnitude_only": False, "normal": False, "school": "Alteration"},
    {"effect": "water_walking", "base_cost": 13, "polarity": "positive", "duration_only": True, "magnitude_only": False, "normal": False, "school": "Alteration"}
]


flower_effects_data2 = {
  "Flower Name": {
    "0": "alkanet_flower",
    "1": "alocasia_fruit",
    "2": "aloe_vera_leaves",
    "3": "ambrosia",
    "4": "apple",
    "5": "arrowroot",
    "6": "beef",
    "7": "bergamot_seeds",
    "8": "blackberry",
    "9": "bloodgrass",
    "10": "boar_meat",
    "11": "bog_beacon_asco_cap",
    "12": "bonemeal*",
    "13": "bread_loaf",
    "14": "cairn_bolete_cap",
    "15": "carrot",
    "16": "cheese_wedge",
    "17": "cheese_wheel",
    "18": "cinnabar_polypore_red_cap",
    "19": "cinnabar_polypore_yellow_cap",
    "20": "clannfear_claws",
    "21": "clouded_funnel_cap",
    "22": "columbine_root_pulp",
    "23": "corn",
    "24": "crab_meat",
    "25": "daedra_heart",
    "26": "daedra_silk",
    "27": "daedra_venin",
    "28": "daedroth_teeth",
    "29": "dragon's_tongue",
    "30": "dreugh_wax",
    "31": "dryad_saddle_polypore_cap",
    "32": "ectoplasm",
    "33": "elf_cup_cap",
    "34": "emetic_russula_cap",
    "35": "fennel_seeds",
    "36": "fire_salts",
    "37": "flax_seeds",
    "38": "flour",
    "39": "fly_amanita_cap",
    "40": "foxglove_nectar",
    "41": "frost_salts",
    "42": "garlic",
    "43": "ginkgo_leaf",
    "44": "ginseng",
    "45": "glow_dust",
    "46": "grapes",
    "47": "green_stain_cup_cap",
    "48": "green_stain_shelf_cap",
    "49": "ham",
    "50": "harrada",
    "51": "imp_gall",
    "52": "ironwood_nut",
    "53": "lady's_mantle_leaves",
    "54": "lady's_smock_leaves",
    "55": "lavender_sprig",
    "56": "leek",
    "57": "lettuce",
    "58": "lichor",
    "59": "mandrake_root",
    "60": "milk_thistle_seeds",
    "61": "minotaur_horn",
    "62": "monkshood_root_pulp",
    "63": "morning_glory_root_pulp",
    "64": "mort_flesh",
    "65": "motherwort_sprig",
    "66": "mugwort_seeds",
    "67": "mutton",
    "68": "nightshade",
    "69": "ogre's_teeth",
    "70": "onion",
    "71": "orange",
    "72": "pear",
    "73": "peony_seeds",
    "74": "potato",
    "75": "primrose_leaves",
    "76": "pumpkin",
    "77": "purgeblood_salts",
    "78": "radish",
    "79": "rat_meat",
    "80": "redwort_flower",
    "81": "rice",
    "82": "root_pulp",
    "83": "sacred_lotus_seeds",
    "84": "scales",
    "85": "scamp_skin",
    "86": "shepherd's_pie",
    "87": "s'jirra's_famous_potato_bread",
    "88": "somnalius_frond",
    "89": "spiddal_stick",
    "90": "st._jahn's_wort_nectar",
    "91": "steel-blue_entoloma_cap",
    "92": "stinkhorn_cap",
    "93": "strawberry",
    "94": "summer_bolete_cap",
    "95": "sweetcake",
    "96": "sweetroll",
    "97": "taproot",
    "98": "tiger_lily_nectar",
    "99": "tinder_polypore_cap",
    "100": "tobacco",
    "101": "tomato",
    "102": "troll_fat",
    "103": "vampire_dust",
    "104": "venison",
    "105": "viper's_bugloss_leaves",
    "106": "void_salts",
    "107": "water_hyacinth_nectar",
    "108": "watermelon",
    "109": "wheat_grain",
    "110": "white_seed_pod",
    "111": "wisp_stalk_caps",
    "112": "wormwood_leaves"
  },
  "Effect 1": {
    "0": " restore_intelligence",
    "1": " restore_fatigue",
    "2": " restore_fatigue",
    "3": " restore_health",
    "4": " restore_fatigue",
    "5": " restore_agility",
    "6": " restore_fatigue",
    "7": " resist_disease",
    "8": " restore_fatigue",
    "9": " chameleon",
    "10": " restore_health",
    "11": " restore_magicka",
    "12": " damage_fatigue",
    "13": " restore_fatigue",
    "14": " restore_health",
    "15": " restore_fatigue",
    "16": " restore_fatigue",
    "17": " restore_fatigue",
    "18": " restore_agility",
    "19": " restore_endurance",
    "20": " cure_disease",
    "21": " restore_intelligence",
    "22": " restore_personality",
    "23": " restore_fatigue",
    "24": " restore_endurance",
    "25": " restore_health",
    "26": " burden",
    "27": " paralyze",
    "28": " night-eye",
    "29": " resist_fire",
    "30": " damage_fatigue",
    "31": " restore_luck",
    "32": " shock_damage",
    "33": " damage_willpower",
    "34": " restore_agility",
    "35": " restore_fatigue",
    "36": " fire_damage",
    "37": " restore_magicka",
    "38": " restore_fatigue",
    "39": " restore_agility",
    "40": " resist_poison",
    "41": " frost_damage",
    "42": " resist_disease",
    "43": " restore_speed",
    "44": " damage_luck",
    "45": " restore_speed",
    "46": " restore_fatigue",
    "47": " restore_fatigue",
    "48": " restore_luck",
    "49": " restore_fatigue",
    "50": " damage_health",
    "51": " fortify_personality",
    "52": " restore_intelligence",
    "53": " restore_health",
    "54": " restore_intelligence",
    "55": " restore_personality",
    "56": " restore_fatigue",
    "57": " restore_fatigue",
    "58": " restore_magicka",
    "59": " cure_disease",
    "60": " light",
    "61": " restore_willpower",
    "62": " restore_strength",
    "63": " burden",
    "64": " damage_fatigue",
    "65": " resist_poison",
    "66": " restore_health",
    "67": " fortify_health",
    "68": " damage_health",
    "69": " damage_intelligence",
    "70": " restore_fatigue",
    "71": " restore_fatigue",
    "72": " restore_fatigue",
    "73": " restore_strength",
    "74": " restore_fatigue",
    "75": " restore_willpower",
    "76": " restore_fatigue",
    "77": " restore_magicka",
    "78": " restore_fatigue",
    "79": " damage_fatigue",
    "80": " resist_frost",
    "81": " restore_fatigue",
    "82": " cure_disease",
    "83": " resist_frost",
    "84": " damage_willpower",
    "85": " damage_magicka",
    "86": " cure_disease",
    "87": " detect_life",
    "88": " restore_speed",
    "89": " damage_health",
    "90": " resist_shock",
    "91": " restore_magicka",
    "92": " damage_health",
    "93": " restore_fatigue",
    "94": " restore_agility",
    "95": " restore_fatigue",
    "96": " restore_fatigue",
    "97": " restore_luck",
    "98": " restore_endurance",
    "99": " restore_willpower",
    "100": " restore_fatigue",
    "101": " restore_fatigue",
    "102": " damage_agility",
    "103": " silence",
    "104": " restore_health",
    "105": " resist_paralysis",
    "106": " restore_magicka",
    "107": " damage_luck",
    "108": " restore_fatigue",
    "109": " restore_fatigue",
    "110": " restore_strength",
    "111": " damage_health",
    "112": " fortify_fatigue"
  },
  "Effect 2": {
    "0": " resist_poison",
    "1": " restore_health",
    "2": " restore_health",
    "3": "reflect_spell",
    "4": " damage_luck",
    "5": " damage_luck",
    "6": " shield",
    "7": " dispel",
    "8": " resist_shock",
    "9": " resist_paralysis",
    "10": " damage_speed",
    "11": " shield",
    "12": " resist_fire",
    "13": " detect_life",
    "14": " damage_intelligence",
    "15": " night-eye",
    "16": " resist_fire",
    "17": " resist_paralysis",
    "18": " shield",
    "19": " fortify_endurance",
    "20": " resist_disease",
    "21": " fortify_intelligence",
    "22": " resist_frost",
    "23": " restore_intelligence",
    "24": " resist_shock",
    "25": " shock_shield",
    "26": " night-eye",
    "27": " restore_fatigue",
    "28": " frost_shield",
    "29": " damage_health",
    "30": " resist_poison",
    "31": " resist_frost",
    "32": " dispel",
    "33": " cure_disease",
    "34": " shield",
    "35": " damage_intelligence",
    "36": " resist_frost",
    "37": " feather",
    "38": " damage_personality",
    "39": " burden",
    "40": " resist_paralysis",
    "41": " resist_fire",
    "42": " damage_agility",
    "43": " fortify_magicka",
    "44": " cure_poison",
    "45": " light",
    "46": " water_walking",
    "47": " damage_speed",
    "48": " fortify_luck",
    "49": " restore_health",
    "50": " damage_magicka",
    "51": " cure_paralysis",
    "52": " resist_fire",
    "53": " damage_endurance",
    "54": " resist_fire",
    "55": " fortify_willpower",
    "56": " fortify_agility",
    "57": " restore_luck",
    "58": "restore_fatigue",
    "59": " resist_poison",
    "60": " frost_damage",
    "61": " burden",
    "62": " damage_intelligence",
    "63": " damage_willpower",
    "64": " damage_luck",
    "65": " damage_fatigue",
    "66": "restore_fatigue",
    "67": " damage_fatigue",
    "68": " burden",
    "69": " resist_paralysis",
    "70": " water_breathing",
    "71": " detect_life",
    "72": " damage_speed",
    "73": " damage_health",
    "74": " shield",
    "75": " restore_personality",
    "76": " damage_agility",
    "77": " damage_health",
    "78": " damage_endurance",
    "79": " detect_life",
    "80": " cure_poison",
    "81": " silence",
    "82": " damage_willpower",
    "83": " damage_health",
    "84": " water_breathing",
    "85": " resist_shock",
    "86": " shield",
    "87": " restore_health",
    "88": " damage_endurance",
    "89": " damage_magicka",
    "90": " damage_health",
    "91": " fire_damage",
    "92": " restore_magicka",
    "93": " cure_poison",
    "94": " shield",
    "95": " feather",
    "96": " resist_disease",
    "97": " damage_endurance",
    "98": " damage_strength",
    "99": " resist_disease",
    "100": " resist_paralysis",
    "101": " detect_life",
    "102": " fortify_personality",
    "103": " resist_disease",
    "104": " feather",
    "105": " night-eye",
    "106": " damage_health",
    "107": " damage_fatigue",
    "108": " light",
    "109": " damage_magicka",
    "110": " water_breathing",
    "111": " damage_willpower",
    "112": " invisibility"
  },
  "Effect 3": {
    "0": " light",
    "1": "light",
    "2": " damage_magicka",
    "3": "reflect_damage",
    "4": " fortify_willpower",
    "5": " fortify_strength",
    "6": " fortify_agility",
    "7": " damage_magicka",
    "8": " fortify_endurance",
    "9": " burden",
    "10": " fortify_health",
    "11": " damage_personality",
    "12": " fortify_luck",
    "13": " damage_agility",
    "14": " resist_paralysis",
    "15": " fortify_intelligence",
    "16": " fire_shield",
    "17": " damage_luck",
    "18": " damage_personality",
    "19": " damage_personality",
    "20": " paralyze",
    "21": " damage_endurance",
    "22": " fortify_magicka",
    "23": " damage_agility",
    "24": " damage_fatigue",
    "25": " damage_magicka",
    "26": " chameleon",
    "27": " damage_health",
    "28": " burden",
    "29": " restore_health",
    "30": " water_breathing",
    "31": " damage_speed",
    "32": " fortify_magicka",
    "33": " fortify_strength",
    "34": " damage_personality",
    "35": " damage_magicka",
    "36": " restore_magicka",
    "37": " shield",
    "38": " fortify_fatigue",
    "39": " restore_health",
    "40": " restore_luck",
    "41": " silence",
    "42": " frost_shield",
    "43": " damage_luck",
    "44": " burden",
    "45": " reflect_spell",
    "46": " dispel",
    "47": " reflect_damage",
    "48": " damage_fatigue",
    "49": " damage_magicka",
    "50": " silence",
    "51": " damage_health",
    "52": " damage_fatigue",
    "53": " night-eye",
    "54": " damage_fatigue",
    "55": " restore_health",
    "56": " damage_personality",
    "57": " fire_shield",
    "58": "restore_health",
    "59": " damage_agility",
    "60": " cure_paralysis",
    "61": " fortify_endurance",
    "62": " fortify_endurance",
    "63": " frost_shield",
    "64": " fortify_health",
    "65": " silence",
    "66": "fortify_fatigue",
    "67": " dispel",
    "68": " damage_luck",
    "69": " shock_damage",
    "70": " detect_life",
    "71": " burden",
    "72": " fortify_speed",
    "73": " damage_speed",
    "74": " burden",
    "75": " fortify_luck",
    "76": " damage_personality",
    "77": " fortify_magicka",
    "78": " chameleon",
    "79": " damage_magicka",
    "80": " damage_health",
    "81": " shock_shield",
    "82": " fortify_strength",
    "83": " feather",
    "84": " damage_health",
    "85": " reflect_damage",
    "86": " fortify_agility",
    "87": " damage_agility",
    "88": " fortify_health",
    "89": " fire_damage",
    "90": " cure_poison",
    "91": " resist_frost",
    "92": " water_walking",
    "93": " damage_health",
    "94": " damage_personality",
    "95": " restore_health",
    "96": " damage_personality",
    "97": " resist_poison",
    "98": " water_walking",
    "99": " invisibility",
    "100": " damage_magicka",
    "101": " burden",
    "102": " damage_willpower",
    "103": " frost_damage",
    "104": " damage_health",
    "105": " burden",
    "106": " fortify_magicka",
    "107": " restore_magicka",
    "108": " burden",
    "109": " fortify_health",
    "110": " silence",
    "111": " damage_intelligence",
    "112": " damage_health"
  },
  "Effect 4": {
    "0": " damage_fatigue",
    "1": "damage_magicka",
    "2": " invisibility",
    "3": "invisibility",
    "4": " damage_health",
    "5": " burden",
    "6": " dispel",
    "7": " silence",
    "8": " restore_magicka",
    "9": " fortify_health",
    "10": " burden",
    "11": " damage_endurance",
    "12": " night-eye",
    "13": " damage_strength",
    "14": " shock_damage",
    "15": " damage_endurance",
    "16": " damage_agility",
    "17": " fortify_willpower",
    "18": " damage_endurance",
    "19": " reflect_spell",
    "20": " damage_health",
    "21": " damage_magicka",
    "22": " chameleon",
    "23": " shock_shield",
    "24": " fire_shield",
    "25": " silence",
    "26": " damage_endurance",
    "27": " reflect_damage",
    "28": " light",
    "29": " fire_shield",
    "30": " damage_health",
    "31": " frost_damage",
    "32": " damage_health",
    "33": " damage_intelligence",
    "34": " damage_endurance",
    "35": " paralyze",
    "36": " fire_shield",
    "37": " damage_health",
    "38": " reflect_damage",
    "39": " shock_damage",
    "40": " resist_disease",
    "41": " frost_shield",
    "42": " fortify_strength",
    "43": " shock_damage",
    "44": " fortify_magicka",
    "45": " damage_health",
    "46": " damage_health",
    "47": " damage_health",
    "48": " restore_health",
    "49": " damage_luck",
    "50": " paralyze",
    "51": " fire_damage",
    "52": " fortify_health",
    "53": " feather",
    "54": " fortify_health",
    "55": " damage_luck",
    "56": " damage_strength",
    "57": " damage_personality",
    "58": "restore_personality",
    "59": " fortify_willpower",
    "60": " paralyze",
    "61": " resist_paralysis",
    "62": " burden",
    "63": " damage_magicka",
    "64": " silence",
    "65": " invisibility",
    "66": "fortify_willpower",
    "67": " damage_magicka",
    "68": " fortify_magicka",
    "69": " fortify_strength",
    "70": " damage_health",
    "71": " shield",
    "72": " damage_health",
    "73": " restore_fatigue",
    "74": " frost_shield",
    "75": " damage_strength",
    "76": " detect_life",
    "77": " dispel",
    "78": " burden",
    "79": " silence",
    "80": " invisibility",
    "81": " damage_agility",
    "82": " damage_intelligence",
    "83": " dispel",
    "84": " water_walking",
    "85": " damage_health",
    "86": " dispel",
    "87": " damage_strength",
    "88": " feather",
    "89": " restore_fatigue",
    "90": " chameleon",
    "91": " burden",
    "92": " invisibility",
    "93": " reflect_damage",
    "94": " damage_endurance",
    "95": " burden",
    "96": " fortify_health",
    "97": " shock_shield",
    "98": " damage_willpower",
    "99": " damage_magicka",
    "100": " dispel",
    "101": " shield",
    "102": " damage_health",
    "103": " invisibility",
    "104": " chameleon",
    "105": " cure_paralysis",
    "106": " dispel",
    "107": " fortify_magicka",
    "108": " damage_health",
    "109": " damage_personality",
    "110": " light",
    "111": " fortify_speed",
    "112": " damage_magicka"
  },
  "Droppable": {
    "0": False,
    "1": False,
    "2": False,
    "3": False,
    "4": False,
    "5": False,
    "6": True,
    "7": False,
    "8": False,
    "9": False,
    "10": True,
    "11": False,
    "12": True,
    "13": True,
    "14": False,
    "15": False,
    "16": True,
    "17": True,
    "18": False,
    "19": False,
    "20": True,
    "21": False,
    "22": False,
    "23": False,
    "24": True,
    "25": True,
    "26": True,
    "27": True,
    "28": True,
    "29": False,
    "30": True,
    "31": False,
    "32": True,
    "33": False,
    "34": False,
    "35": False,
    "36": True,
    "37": False,
    "38": True,
    "39": False,
    "40": False,
    "41": True,
    "42": False,
    "43": False,
    "44": False,
    "45": True,
    "46": False,
    "47": False,
    "48": False,
    "49": True,
    "50": False,
    "51": True,
    "52": False,
    "53": False,
    "54": False,
    "55": False,
    "56": False,
    "57": False,
    "58": False,
    "59": False,
    "60": False,
    "61": True,
    "62": False,
    "63": False,
    "64": True,
    "65": False,
    "66": False,
    "67": True,
    "68": False,
    "69": True,
    "70": False,
    "71": False,
    "72": False,
    "73": False,
    "74": False,
    "75": False,
    "76": False,
    "77": True,
    "78": False,
    "79": True,
    "80": False,
    "81": False,
    "82": False,
    "83": False,
    "84": True,
    "85": True,
    "86": True,
    "87": True,
    "88": False,
    "89": False,
    "90": False,
    "91": False,
    "92": False,
    "93": False,
    "94": False,
    "95": False,
    "96": False,
    "97": True,
    "98": False,
    "99": False,
    "100": False,
    "101": False,
    "102": True,
    "103": True,
    "104": True,
    "105": False,
    "106": True,
    "107": False,
    "108": False,
    "109": False,
    "110": False,
    "111": False,
    "112": False
  },
  "Wieght": {
    "0": 0.1,
    "1": 0.2,
    "2": 0.3,
    "3": 0.1,
    "4": 0.2,
    "5": 0.1,
    "6": 1.0,
    "7": 0.1,
    "8": 0.1,
    "9": 0.1,
    "10": 2.0,
    "11": 0.1,
    "12": 0.1,
    "13": 0.3,
    "14": 0.1,
    "15": 0.1,
    "16": 1.0,
    "17": 2.0,
    "18": 0.1,
    "19": 0.1,
    "20": 2.0,
    "21": 0.1,
    "22": 0.1,
    "23": 0.5,
    "24": 1.0,
    "25": 1.0,
    "26": 1.0,
    "27": 1.0,
    "28": 2.0,
    "29": 0.1,
    "30": 0.1,
    "31": 0.1,
    "32": 0.1,
    "33": 0.1,
    "34": 0.1,
    "35": 0.1,
    "36": 0.5,
    "37": 0.1,
    "38": 0.3,
    "39": 0.1,
    "40": 0.1,
    "41": 0.5,
    "42": 0.1,
    "43": 0.1,
    "44": 0.1,
    "45": 0.4,
    "46": 0.7,
    "47": 0.1,
    "48": 0.1,
    "49": 2.0,
    "50": 0.1,
    "51": 0.3,
    "52": 0.1,
    "53": 0.1,
    "54": 0.1,
    "55": 0.1,
    "56": 0.4,
    "57": 0.5,
    "58": 0.5,
    "59": 0.1,
    "60": 0.1,
    "61": 5.0,
    "62": 0.1,
    "63": 0.1,
    "64": 3.0,
    "65": 0.1,
    "66": 0.1,
    "67": 2.0,
    "68": 0.1,
    "69": 1.0,
    "70": 0.2,
    "71": 0.2,
    "72": 0.2,
    "73": 0.1,
    "74": 1.0,
    "75": 0.1,
    "76": 5.0,
    "77": 0.1,
    "78": 0.1,
    "79": 2.0,
    "80": 0.1,
    "81": 0.1,
    "82": 0.1,
    "83": 0.1,
    "84": 0.3,
    "85": 1.0,
    "86": 1.0,
    "87": 2.0,
    "88": 0.2,
    "89": 0.5,
    "90": 0.1,
    "91": 0.1,
    "92": 0.1,
    "93": 0.1,
    "94": 0.1,
    "95": 0.4,
    "96": 0.4,
    "97": 1.0,
    "98": 0.1,
    "99": 0.1,
    "100": 0.4,
    "101": 0.2,
    "102": 3.0,
    "103": 0.1,
    "104": 2.0,
    "105": 0.1,
    "106": 0.4,
    "107": 0.1,
    "108": 5.0,
    "109": 0.1,
    "110": 0.1,
    "111": 0.1,
    "112": 0.1
  },
  "Description": {
    "0": "A pokey ",
    "1": "A pokey ",
    "2": " Aloe Vera tends to be most plentiful in coastal locations, such as Blackwood and the Gold Coast. Many Aloe Vera grow in Anvil, both in the town itself and by the docks. Some can be found south of Gottshaw Inn.",
    "3": "A pokey ",
    "4": "A pokey ",
    "5": "A pokey ",
    "6": "A pokey ",
    "7": "A pokey ",
    "8": "A pokey ",
    "9": "A pokey ",
    "10": "A pokey ",
    "11": "A pokey ",
    "12": "A pokey ",
    "13": "A pokey ",
    "14": "A pokey ",
    "15": "A pokey ",
    "16": "A pokey ",
    "17": "A pokey ",
    "18": "A pokey ",
    "19": "A pokey ",
    "20": "A pokey ",
    "21": "A pokey ",
    "22": "A pokey ",
    "23": "A pokey ",
    "24": "A pokey ",
    "25": "A pokey ",
    "26": "A pokey ",
    "27": "A pokey ",
    "28": "A pokey ",
    "29": "A pokey ",
    "30": "A pokey ",
    "31": "A pokey ",
    "32": "A pokey ",
    "33": "A pokey ",
    "34": "A pokey ",
    "35": "A pokey ",
    "36": "A pokey ",
    "37": "A pokey ",
    "38": "A pokey ",
    "39": "A pokey ",
    "40": "A pokey ",
    "41": "A pokey ",
    "42": "A pokey ",
    "43": "A pokey ",
    "44": "A pokey ",
    "45": "A pokey ",
    "46": "A pokey ",
    "47": "A pokey ",
    "48": "A pokey ",
    "49": "A pokey ",
    "50": "A pokey ",
    "51": "A pokey ",
    "52": "A pokey ",
    "53": "A pokey ",
    "54": "A pokey ",
    "55": "A pokey ",
    "56": "A pokey ",
    "57": "A pokey ",
    "58": "A pokey ",
    "59": "A pokey ",
    "60": "A pokey ",
    "61": "A pokey ",
    "62": "A pokey ",
    "63": "A pokey ",
    "64": "A pokey ",
    "65": "A pokey ",
    "66": "A pokey ",
    "67": "A pokey ",
    "68": "A pokey ",
    "69": "A pokey ",
    "70": "A pokey ",
    "71": "A pokey ",
    "72": "A pokey ",
    "73": "A pokey ",
    "74": "A pokey ",
    "75": "A pokey ",
    "76": "A pokey ",
    "77": "A pokey ",
    "78": "A pokey ",
    "79": "A pokey ",
    "80": "A pokey ",
    "81": "A pokey ",
    "82": "A pokey ",
    "83": "A pokey ",
    "84": "A pokey ",
    "85": "A pokey ",
    "86": "A pokey ",
    "87": "A pokey ",
    "88": "A pokey ",
    "89": "A pokey ",
    "90": "A pokey ",
    "91": "A pokey ",
    "92": "A pokey ",
    "93": "A pokey ",
    "94": "A pokey ",
    "95": "A pokey ",
    "96": "A pokey ",
    "97": "A pokey ",
    "98": "A pokey ",
    "99": "A pokey ",
    "100": "A pokey ",
    "101": "A pokey ",
    "102": "A pokey ",
    "103": "A pokey ",
    "104": "A pokey ",
    "105": "A pokey ",
    "106": "A pokey ",
    "107": "A pokey ",
    "108": "A pokey ",
    "109": "A pokey ",
    "110": "A pokey ",
    "111": "A pokey ",
    "112": "A pokey "
    }
}






# flower_effects_data = [
#     {"Flower Name": "alkanet_flower", "Effect 1": "restore_intelligence", "Effect 2": "resist_poison", "Effect 3": "light", "Effect 4": "damage_fatigue", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "alocasia_fruit", "Effect 1": "restore_fatigue", "Effect 2": "restore_health", "Effect 3": "light", "Effect 4": "damage_magicka", "Droppable": False, "Wieght": 0.2, "Description": "A pokey"},
#     {"Flower Name": "aloe_vera_leaves", "Effect 1": "restore_fatigue", "Effect 2": "restore_health", "Effect 3": "damage_magicka", "Effect 4": "invisibility", "Droppable": False, "Wieght": 0.3, "Description": "Aloe Vera tends to be most plentiful in coastal locations, such as Blackwood and the Gold Coast. Many Aloe Vera grow in Anvil, both in the town itself and by the docks. Some can be found south of Gottshaw Inn."},
#     {"Flower Name": "ambrosia", "Effect 1": "restore_health", "Effect 2": "reflect_spell", "Effect 3": "reflect_damage", "Effect 4": "invisibility", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "apple", "Effect 1": "restore_fatigue", "Effect 2": "damage_luck", "Effect 3": "fortify_willpower", "Effect 4": "damage_health", "Droppable": False, "Wieght": 0.2, "Description": "A pokey"},
#     {"Flower Name": "arrowroot", "Effect 1": "restore_agility", "Effect 2": "damage_luck", "Effect 3": "fortify_strength", "Effect 4": "burden", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "beef", "Effect 1": "restore_fatigue", "Effect 2": "shield", "Effect 3": "fortify_agility", "Effect 4": "dispel", "Droppable": True, "Wieght": 1, "Description": "A pokey"},
#     {"Flower Name": "bergamot_seeds", "Effect 1": "resist_disease", "Effect 2": "dispel", "Effect 3": "damage_magicka", "Effect 4": "silence", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "blackberry", "Effect 1": "restore_fatigue", "Effect 2": "resist_shock", "Effect 3": "fortify_endurance", "Effect 4": "restore_magicka", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "bloodgrass", "Effect 1": "chameleon", "Effect 2": "resist_paralysis", "Effect 3": "burden", "Effect 4": "fortify_health", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "boar_meat", "Effect 1": "restore_health", "Effect 2": "damage_speed", "Effect 3": "fortify_health", "Effect 4": "burden", "Droppable": True, "Wieght": 2, "Description": "A pokey"},
#     {"Flower Name": "bog_beacon_asco_cap", "Effect 1": "restore_magicka", "Effect 2": "shield", "Effect 3": "damage_personality", "Effect 4": "damage_endurance", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "bonemeal*", "Effect 1": "damage_fatigue", "Effect 2": "resist_fire", "Effect 3": "fortify_luck", "Effect 4": "night-eye", "Droppable": True, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "bread_loaf", "Effect 1": "restore_fatigue", "Effect 2": "detect_life", "Effect 3": "damage_agility", "Effect 4": "damage_strength", "Droppable": True, "Wieght": 0.3, "Description": "A pokey"},
#     {"Flower Name": "cairn_bolete_cap", "Effect 1": "restore_health", "Effect 2": "damage_intelligence", "Effect 3": "resist_paralysis", "Effect 4": "shock_damage", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "carrot", "Effect 1": "restore_fatigue", "Effect 2": "night-eye", "Effect 3": "fortify_intelligence", "Effect 4": "damage_endurance", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "cheese_wedge", "Effect 1": "restore_fatigue", "Effect 2": "resist_fire", "Effect 3": "fire_shield", "Effect 4": "damage_agility", "Droppable": True, "Wieght": 1, "Description": "A pokey"},
#     {"Flower Name": "cheese_wheel", "Effect 1": "restore_fatigue", "Effect 2": "resist_paralysis", "Effect 3": "damage_luck", "Effect 4": "fortify_willpower", "Droppable": True, "Wieght": 2, "Description": "A pokey"},
#     {"Flower Name": "cinnabar_polypore_red_cap", "Effect 1": "restore_agility", "Effect 2": "shield", "Effect 3": "damage_personality", "Effect 4": "damage_endurance", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "cinnabar_polypore_yellow_cap", "Effect 1": "restore_endurance", "Effect 2": "fortify_endurance", "Effect 3": "damage_personality", "Effect 4": "reflect_spell", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "clannfear_claws", "Effect 1": "cure_disease", "Effect 2": "resist_disease", "Effect 3": "paralyze", "Effect 4": "damage_health", "Droppable": True, "Wieght": 2, "Description": "A pokey"},
#     {"Flower Name": "clouded_funnel_cap", "Effect 1": "restore_intelligence", "Effect 2": "fortify_intelligence", "Effect 3": "damage_endurance", "Effect 4": "damage_magicka", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "columbine_root_pulp", "Effect 1": "restore_personality", "Effect 2": "resist_frost", "Effect 3": "fortify_magicka", "Effect 4": "chameleon", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "corn", "Effect 1": "restore_fatigue", "Effect 2": "restore_intelligence", "Effect 3": "damage_agility", "Effect 4": "shock_shield", "Droppable": False, "Wieght": 0.5, "Description": "A pokey"},
#     {"Flower Name": "crab_meat", "Effect 1": "restore_endurance", "Effect 2": "resist_shock", "Effect 3": "damage_fatigue", "Effect 4": "fire_shield", "Droppable": True, "Wieght": 1, "Description": "A pokey"},
#     {"Flower Name": "daedra_heart", "Effect 1": "restore_health", "Effect 2": "shock_shield", "Effect 3": "damage_magicka", "Effect 4": "silence", "Droppable": True, "Wieght": 1, "Description": "A pokey"},
#     {"Flower Name": "daedra_silk", "Effect 1": "burden", "Effect 2": "night-eye", "Effect 3": "chameleon", "Effect 4": "damage_endurance", "Droppable": True, "Wieght": 1, "Description": "A pokey"},
#     {"Flower Name": "daedra_venin", "Effect 1": "paralyze", "Effect 2": "restore_fatigue", "Effect 3": "damage_health", "Effect 4": "reflect_damage", "Droppable": True, "Wieght": 1, "Description": "A pokey"},
#     {"Flower Name": "daedroth_teeth", "Effect 1": "night-eye", "Effect 2": "frost_shield", "Effect 3": "burden", "Effect 4": "light", "Droppable": True, "Wieght": 2, "Description": "A pokey"},
#     {"Flower Name": "dragon's_tongue", "Effect 1": "resist_fire", "Effect 2": "damage_health", "Effect 3": "restore_health", "Effect 4": "fire_shield", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "dreugh_wax", "Effect 1": "damage_fatigue", "Effect 2": "resist_poison", "Effect 3": "water_breathing", "Effect 4": "damage_health", "Droppable": True, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "dryad_saddle_polypore_cap", "Effect 1": "restore_luck", "Effect 2": "resist_frost", "Effect 3": "damage_speed", "Effect 4": "frost_damage", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "ectoplasm", "Effect 1": "shock_damage", "Effect 2": "dispel", "Effect 3": "fortify_magicka", "Effect 4": "damage_health", "Droppable": True, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "elf_cup_cap", "Effect 1": "damage_willpower", "Effect 2": "cure_disease", "Effect 3": "fortify_strength", "Effect 4": "damage_intelligence", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "emetic_russula_cap", "Effect 1": "restore_agility", "Effect 2": "shield", "Effect 3": "damage_personality", "Effect 4": "damage_endurance", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "fennel_seeds", "Effect 1": "restore_fatigue", "Effect 2": "damage_intelligence", "Effect 3": "damage_magicka", "Effect 4": "paralyze", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "fire_salts", "Effect 1": "fire_damage", "Effect 2": "resist_frost", "Effect 3": "restore_magicka", "Effect 4": "fire_shield", "Droppable": True, "Wieght": 0.5, "Description": "A pokey"},
#     {"Flower Name": "flax_seeds", "Effect 1": "restore_magicka", "Effect 2": "feather", "Effect 3": "shield", "Effect 4": "damage_health", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "flour", "Effect 1": "restore_fatigue", "Effect 2": "damage_personality", "Effect 3": "fortify_fatigue", "Effect 4": "reflect_damage", "Droppable": True, "Wieght": 0.3, "Description": "A pokey"},
#     {"Flower Name": "fly_amanita_cap", "Effect 1": "restore_agility", "Effect 2": "burden", "Effect 3": "restore_health", "Effect 4": "shock_damage", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "foxglove_nectar", "Effect 1": "resist_poison", "Effect 2": "resist_paralysis", "Effect 3": "restore_luck", "Effect 4": "resist_disease", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "frost_salts", "Effect 1": "frost_damage", "Effect 2": "resist_fire", "Effect 3": "silence", "Effect 4": "frost_shield", "Droppable": True, "Wieght": 0.5, "Description": "A pokey"},
#     {"Flower Name": "garlic", "Effect 1": "resist_disease", "Effect 2": "damage_agility", "Effect 3": "frost_shield", "Effect 4": "fortify_strength", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "ginkgo_leaf", "Effect 1": "restore_speed", "Effect 2": "fortify_magicka", "Effect 3": "damage_luck", "Effect 4": "shock_damage", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "ginseng", "Effect 1": "damage_luck", "Effect 2": "cure_poison", "Effect 3": "burden", "Effect 4": "fortify_magicka", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "glow_dust", "Effect 1": "restore_speed", "Effect 2": "light", "Effect 3": "reflect_spell", "Effect 4": "damage_health", "Droppable": True, "Wieght": 0.4, "Description": "A pokey"},
#     {"Flower Name": "grapes", "Effect 1": "restore_fatigue", "Effect 2": "water_walking", "Effect 3": "dispel", "Effect 4": "damage_health", "Droppable": False, "Wieght": 0.7, "Description": "A pokey"},
#     {"Flower Name": "green_stain_cup_cap", "Effect 1": "restore_fatigue", "Effect 2": "damage_speed", "Effect 3": "reflect_damage", "Effect 4": "damage_health", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "green_stain_shelf_cap", "Effect 1": "restore_luck", "Effect 2": "fortify_luck", "Effect 3": "damage_fatigue", "Effect 4": "restore_health", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "ham", "Effect 1": "restore_fatigue", "Effect 2": "restore_health", "Effect 3": "damage_magicka", "Effect 4": "damage_luck", "Droppable": True, "Wieght": 2, "Description": "A pokey"},
#     {"Flower Name": "harrada", "Effect 1": "damage_health", "Effect 2": "damage_magicka", "Effect 3": "silence", "Effect 4": "paralyze", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "imp_gall", "Effect 1": "fortify_personality", "Effect 2": "cure_paralysis", "Effect 3": "damage_health", "Effect 4": "fire_damage", "Droppable": True, "Wieght": 0.3, "Description": "A pokey"},
#     {"Flower Name": "ironwood_nut", "Effect 1": "restore_intelligence", "Effect 2": "resist_fire", "Effect 3": "damage_fatigue", "Effect 4": "fortify_health", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "lady's_mantle_leaves", "Effect 1": "restore_endurance", "Effect 2": "reflect_spell", "Effect 3": "fortify_health", "Effect 4": "damage_luck", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "lady's_smock_leaves", "Effect 1": "restore_endurance", "Effect 2": "fortify_speed", "Effect 3": "damage_health", "Effect 4": "fortify_intelligence", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "lava_salts", "Effect 1": "fire_damage", "Effect 2": "resist_frost", "Effect 3": "silence", "Effect 4": "fire_shield", "Droppable": True, "Wieght": 0.5, "Description": "A pokey"},
#     {"Flower Name": "lemon", "Effect 1": "restore_fatigue", "Effect 2": "resist_disease", "Effect 3": "damage_health", "Effect 4": "resist_frost", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "lettuce", "Effect 1": "restore_fatigue", "Effect 2": "resist_fire", "Effect 3": "damage_luck", "Effect 4": "damage_speed", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "mandrake_root", "Effect 1": "night-eye", "Effect 2": "damage_speed", "Effect 3": "damage_health", "Effect 4": "restore_speed", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "marshmerrow*", "Effect 1": "restore_health", "Effect 2": "feather", "Effect 3": "invisibility", "Effect 4": "fortify_willpower", "Droppable": True, "Wieght": 0.3, "Description": "A pokey"},
#     {"Flower Name": "masterwort_flower", "Effect 1": "restore_speed", "Effect 2": "resist_poison", "Effect 3": "damage_personality", "Effect 4": "fortify_endurance", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "meat", "Effect 1": "restore_fatigue", "Effect 2": "resist_disease", "Effect 3": "damage_health", "Effect 4": "damage_luck", "Droppable": True, "Wieght": 1, "Description": "A pokey"},
#     {"Flower Name": "milk", "Effect 1": "restore_fatigue", "Effect 2": "resist_poison", "Effect 3": "damage_willpower", "Effect 4": "damage_luck", "Droppable": True, "Wieght": 0.5, "Description": "A pokey"},
#     {"Flower Name": "miner's_saltpeter*", "Effect 1": "damage_intelligence", "Effect 2": "damage_magicka", "Effect 3": "silence", "Effect 4": "fire_damage", "Droppable": True, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "mugwort_seeds", "Effect 1": "restore_luck", "Effect 2": "cure_poison", "Effect 3": "damage_health", "Effect 4": "fortify_speed", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "namira's_rot", "Effect 1": "damage_health", "Effect 2": "restore_health", "Effect 3": "cure_poison", "Effect 4": "fortify_health", "Droppable": True, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "nirnroot*", "Effect 1": "restore_health", "Effect 2": "night-eye", "Effect 3": "damage_agility", "Effect 4": "damage_strength", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "ogre's_teeth", "Effect 1": "fortify_agility", "Effect 2": "damage_speed", "Effect 3": "burden", "Effect 4": "damage_health", "Droppable": True, "Wieght": 1, "Description": "A pokey"},
#     {"Flower Name": "onion", "Effect 1": "restore_fatigue", "Effect 2": "damage_personality", "Effect 3": "damage_health", "Effect 4": "resist_poison", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "orange", "Effect 1": "restore_fatigue", "Effect 2": "restore_agility", "Effect 3": "damage_health", "Effect 4": "damage_magicka", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "penny_bun_mushroom_cap", "Effect 1": "restore_luck", "Effect 2": "restore_personality", "Effect 3": "damage_health", "Effect 4": "fortify_willpower", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "peony_seeds", "Effect 1": "restore_strength", "Effect 2": "cure_poison", "Effect 3": "damage_health", "Effect 4": "fortify_endurance", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "plum", "Effect 1": "restore_fatigue", "Effect 2": "fortify_willpower", "Effect 3": "damage_health", "Effect 4": "resist_poison", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "pumpkin", "Effect 1": "restore_fatigue", "Effect 2": "feather", "Effect 3": "burden", "Effect 4": "damage_health", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "rice", "Effect 1": "restore_health", "Effect 2": "resist_poison", "Effect 3": "damage_magicka", "Effect 4": "resist_frost", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "roses_of_sithis*", "Effect 1": "damage_willpower", "Effect 2": "fortify_agility", "Effect 3": "damage_fatigue", "Effect 4": "night-eye", "Droppable": True, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "saffron", "Effect 1": "restore_agility", "Effect 2": "damage_magicka", "Effect 3": "damage_health", "Effect 4": "fortify_fatigue", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "salt_rice", "Effect 1": "restore_health", "Effect 2": "restore_magicka", "Effect 3": "resist_poison", "Effect 4": "damage_magicka", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "scalon_fin", "Effect 1": "restore_health", "Effect 2": "water_breathing", "Effect 3": "resist_frost", "Effect 4": "damage_health", "Droppable": True, "Wieght": 1, "Description": "A pokey"},
#     {"Flower Name": "scathecraw*", "Effect 1": "damage_agility", "Effect 2": "damage_luck", "Effect 3": "damage_speed", "Effect 4": "fortify_health", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "seaweed", "Effect 1": "restore_endurance", "Effect 2": "resist_poison", "Effect 3": "restore_speed", "Effect 4": "damage_strength", "Droppable": True, "Wieght": 0.5, "Description": "A pokey"},
#     {"Flower Name": "skooma", "Effect 1": "restore_agility", "Effect 2": "fortify_strength", "Effect 3": "damage_willpower", "Effect 4": "damage_health", "Droppable": True, "Wieght": 0.5, "Description": "A pokey"},
#     {"Flower Name": "snowberries*", "Effect 1": "restore_endurance", "Effect 2": "restore_magicka", "Effect 3": "damage_fatigue", "Effect 4": "resist_frost", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "stinkhorn_cap", "Effect 1": "restore_agility", "Effect 2": "shield", "Effect 3": "damage_personality", "Effect 4": "damage_endurance", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "strawberry", "Effect 1": "restore_fatigue", "Effect 2": "fortify_speed", "Effect 3": "damage_health", "Effect 4": "damage_luck", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "sweetcake", "Effect 1": "restore_health", "Effect 2": "restore_stamina", "Effect 3": "damage_magicka", "Effect 4": "fortify_willpower", "Droppable": True, "Wieght": 0.4, "Description": "A pokey"},
#     {"Flower Name": "tinder_polypore_cap", "Effect 1": "restore_personality", "Effect 2": "damage_health", "Effect 3": "restore_speed", "Effect 4": "damage_strength", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "tomato", "Effect 1": "restore_fatigue", "Effect 2": "damage_strength", "Effect 3": "fortify_strength", "Effect 4": "resist_fire", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "viper's_bugloss_leaves", "Effect 1": "restore_strength", "Effect 2": "damage_willpower", "Effect 3": "damage_health", "Effect 4": "fortify_speed", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "void_salts", "Effect 1": "shock_damage", "Effect 2": "resist_magic", "Effect 3": "damage_health", "Effect 4": "fire_shield", "Droppable": True, "Wieght": 0.5, "Description": "A pokey"},
#     {"Flower Name": "watermelon", "Effect 1": "restore_fatigue", "Effect 2": "restore_magicka", "Effect 3": "damage_health", "Effect 4": "damage_luck", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "wisp_stalk_caps", "Effect 1": "restore_luck", "Effect 2": "fortify_strength", "Effect 3": "damage_health", "Effect 4": "restore_health", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "wolfsbane_petals", "Effect 1": "restore_strength", "Effect 2": "resist_poison", "Effect 3": "damage_health", "Effect 4": "fortify_strength", "Droppable": False, "Wieght": 0.1, "Description": "A pokey"},
#     {"Flower Name": "wormwood_leaves", "Effect 1": "fortify_strength", "Effect 2": "damage_luck", "Effect 3": ""


def pretty_string(namestring):
	return namestring.replace('_', ' ').title()