
#these potion instances should ONLY be generated by the Alchemy object
class PotionInstance:
	def __init__(self, magnitude=None, duration=None):
		self.magnitude = 0
		self.polarity = 0

class PotionFactory:
	def __init__(self):
		self.magnitude = 0
		self.polarity = 0

